#!/bin/sh

ROUTES=/etc/tinc/${NETNAME}/hosts/${NODE}-routes

host_up() {
	if [ -f $ROUTES ]; then
		xargs -iROUTE -t ip route add ROUTE dev $INTERFACE proto 42 < $ROUTES
	fi
}

host_down() {
	if [ -f $ROUTES ]; then
		xargs -iROUTE -t ip route del ROUTE dev $INTERFACE proto 42 < $ROUTES
	fi
}

case $0 in
	(*-down)
	host_down
	;;

	(*-up)
	host_up
	;;
esac
